name: mkdocs
on: push
permissions:
  contents: write
jobs:
  docs:
    # prevent this action from running on forks
    if: |
      github.repository == 'dgaines2/vasp_manager' &&
      startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -e '.[docs]'
    - name: Build Docs
      run: |
        mkdocs build
    - name: Rebuild and deploy docs
      run: mkdocs gh-deploy --force
