name: Publish to PyPI

on: push

jobs:
  build:
    # prevent this action from running on forks
    if: github.repository == 'dgaines2/vasp_manager'
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install build --user
        python -m pip install .
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
  
  publish-to-pypi:
    # prevent this action from running on forks
    if: |
      github.repository == 'dgaines2/vasp_manager' &&
      startsWith(github.ref, 'refs/tags/')
    name: Publish Python to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/vasp-manager
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
